### ISSUE TITLE
Screenshots will be highly appreciated 😀

### ISSUE THREAD

**Issue by alvaropinot** [vizeat/storybook-addon-responsive-views#1]
When it comes to visual plugins or so a screenshot or a gif will is really helpful to check if the given look is what the user is looking for.

If or when I try your plugin I'll try to send some.

Thanks 🙏 for sharing and sorry if I missed them! 😄

**Comment by juliamitchelmore** [comment]
I've added a screenshot to the main README @alvaropinot, hopefully that should give you a better idea of what's going on 👍
