### ISSUE TITLE
Convert from panel addon to toolbar addon

### ISSUE THREAD

**Issue by CodeByAlex** [vizeat/storybook-addon-responsive-views#2]
Since the only element shown in the addon panel is a toggle checkbox to turin on and off the addon, this would probably be great to be used as a toolbar addon. Ex:

![image](https://user-images.githubusercontent.com/29763590/62576779-81c9ac80-b86b-11e9-8cd9-13d07d0687ec.png)

**Comment by p-j** [comment]
Hi @CodeByAlex 
Thanks for your suggestion. We'll take it onboard with @juliamitchelmore.

**Comment by juliamitchelmore** [comment]
Thanks @CodeByAlex, great suggestion! If you upgrade to v2.0.1, the addon has been converted to a toolbar toggle 👍
