### ISSUE TITLE
Module not found: Error: Can't resolve './ResponsiveView'

### ISSUE THREAD

**Issue by jalooc** [vizeat/storybook-addon-responsive-views#4]
![image](https://user-images.githubusercontent.com/6209244/69893225-d692a680-12e4-11ea-85c0-96931fff7dea.png)

For version `2.2.0`
Works for `2.1.0` (the modules is present)

**Comment by p-j** [comment]
Hi @jalooc 
Thanks for the report, I just uploaded a new version that should fix this. (2.2.3)
