### ISSUE TITLE
The component displays outside of the generated viewports

### ISSUE THREAD

**Issue by jalooc** [vizeat/storybook-addon-responsive-views#5]
![image](https://user-images.githubusercontent.com/6209244/69893331-3f2e5300-12e6-11ea-8875-ed8ef035f662.png)

This happens for version `2.1.0` ([can't test it with the newest `2.2.0`](https://github.com/vizeat/storybook-addon-responsive-views/issues/4)).

Testing conditions:
* no addons
* tried with both global and local decorators
* using [CSF](https://storybook.js.org/docs/formats/component-story-format/) to write stories

I'll be happy to provide more information if needed.

**Comment by p-j** [comment]
Hi @jalooc 
now that your other issue is fixed would you mind testing with the new version?

We do not use CSF in our internal storybook yet, if this is linked we'll certainly investigate as we migrate to it.
In the meantime if you have an idea of how to fix this, please do not hesitate to draft a PR.
