### ISSUE TITLE
Angular compability

### ISSUE THREAD

**Issue by alexchitoraga** [vizeat/storybook-addon-responsive-views#6]
As Storybook is mainly created for React, this package is supported only by React. Is there any plans about extending compatibility for Angular?

**Comment by p-j** [comment]
Hi @alexchitoraga 

We don't have plan on adding this ourselves as we don't use Angular at Eatwith.
However, we welcome pull requests and if you are willing to do it we'll happily review it and help you get it merged in!

**Comment by ibnYusrat** [comment]
It would be really polite to mention this somewhere prominently in the README.md that the plugin is not supported for Angular to save people's time.

**Comment by p-j** [comment]
Thanks for the suggestion @ibnYusrat, I just added a note about compatibility https://github.com/vizeat/storybook-addon-responsive-views/commit/356e7a7839195d725d15394a681a810f87f22513

Feel free to send PR to improve the Readme as well by the way, that's often the easiest way to start contributing to open source projects like this one.

**Comment by jvinters** [comment]
+1 for angular support

**Comment by 54mu3l** [comment]
+1 for vue support

**Comment by Dan503** [comment]
+1 for Svelte support
